package view;

import java.awt.Color;
import static utils.DataValidation.calculateNifLetter;
import static utils.DataValidation.checkEmailAddress;
import static utils.DataValidation.isLetter;
import static utils.DataValidation.isNumber;

import java.awt.dnd.DropTarget;
import java.awt.event.KeyEvent;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import org.jdatepicker.DateModel;
import org.jdatepicker.JDatePicker;
import static utils.DataValidation.checkPhoneNumber;
import static utils.DataValidation.checkZipCodeTyping;

/**
 * Interface used to register a person. It is mandatory to enter at least the
 * NIF and the name.
 *
 * @author Francesc Perez
 * @version 1.1.0
 */
public class Insert extends javax.swing.JDialog {

    public Insert(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        DropPhotoListener d = new DropPhotoListener(photo, this);
        DropTarget dropTarget = new DropTarget(photo, d);
        insert.setEnabled(false);
        customDatePicker();
    }

    public JButton getReset() {
        return reset;
    }

    public JButton getInsert() {
        return insert;
    }

    public JTextField getNam() {
        return name;
    }

    public JDatePicker getDateOfBirth() {
        return dateOfBirth;
    }

    public JTextField getNif() {
        return nif;
    }

    public JLabel getPhoto() {
        return photo;
    }

    public JTextField getEmail() {
        return email;
    }

    public JCheckBox getCheck() {
        return EmailIsValidCheck;
    }

    public JCheckBox getPhoneCheck() {
        return PhoneValidCheck;
    }

    public JTextField getPhone() {
        return phone;
    }

    public JTextField getZipCode() {
        return zipCode;
    }
    
    private void customDatePicker(){
        JButton updatedButton = dateOfBirth.getButton();
        updatedButton.setText("SELECT A DATE");
        updatedButton.setPreferredSize(new java.awt.Dimension(110, 50));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        insert = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        reset = new javax.swing.JButton();
        photo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nif = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dateOfBirth = new org.jdatepicker.JDatePicker();
        jLabel3 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        checkEmailField = new javax.swing.JButton();
        EmailIsValidCheck = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        checkPhoneField = new javax.swing.JButton();
        PhoneValidCheck = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        zipCode = new javax.swing.JTextField();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Insert - People v1.1.0");
        setMinimumSize(new java.awt.Dimension(810, 280));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        insert.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        insert.setText("INSERT");
        insert.setMaximumSize(new java.awt.Dimension(187, 33));
        insert.setMinimumSize(new java.awt.Dimension(187, 33));
        insert.setPreferredSize(new java.awt.Dimension(187, 33));
        getContentPane().add(insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 258, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Email");
        jLabel1.setMaximumSize(new java.awt.Dimension(100, 22));
        jLabel1.setMinimumSize(new java.awt.Dimension(100, 22));
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 22));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 108, 150, -1));

        name.setForeground(new java.awt.Color(153, 153, 153));
        name.setText("Enter full name");
        name.setMaximumSize(new java.awt.Dimension(400, 22));
        name.setMinimumSize(new java.awt.Dimension(400, 22));
        name.setPreferredSize(new java.awt.Dimension(400, 22));
        name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameFocusLost(evt);
            }
        });
        name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameKeyTyped(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 68, -1, -1));

        reset.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        reset.setText("RESET");
        reset.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reset.setMaximumSize(new java.awt.Dimension(187, 33));
        reset.setMinimumSize(new java.awt.Dimension(187, 33));
        reset.setPreferredSize(new java.awt.Dimension(187, 33));
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 258, 189, -1));

        photo.setBackground(new java.awt.Color(255, 255, 255));
        photo.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        photo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        photo.setText("<html><center><center>Drag and drop your file here</center><br><br>PHOTO</center></br><br><center> <i>Supported format: PNG.</i></center></br><br><center><i>Max. size 64KB</i></center></html>");
        photo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        photo.setMaximumSize(new java.awt.Dimension(150, 135));
        photo.setMinimumSize(new java.awt.Dimension(150, 135));
        photo.setPreferredSize(new java.awt.Dimension(150, 135));
        photo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                photoMouseClicked(evt);
            }
        });
        getContentPane().add(photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 16, -1, 171));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("NIF");
        jLabel5.setMaximumSize(new java.awt.Dimension(100, 22));
        jLabel5.setMinimumSize(new java.awt.Dimension(100, 22));
        jLabel5.setPreferredSize(new java.awt.Dimension(100, 22));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 28, 150, -1));

        nif.setForeground(new java.awt.Color(153, 153, 153));
        nif.setText("Enter NIF number, letter is calculated (e.g., 12345678)");
        nif.setMaximumSize(new java.awt.Dimension(400, 22));
        nif.setMinimumSize(new java.awt.Dimension(400, 22));
        nif.setPreferredSize(new java.awt.Dimension(400, 22));
        nif.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nifFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nifFocusLost(evt);
            }
        });
        nif.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nifKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nifKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nifKeyTyped(evt);
            }
        });
        getContentPane().add(nif, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 28, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Date of Birth");
        jLabel8.setMaximumSize(new java.awt.Dimension(150, 22));
        jLabel8.setMinimumSize(new java.awt.Dimension(150, 22));
        jLabel8.setPreferredSize(new java.awt.Dimension(150, 22));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 233, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 8)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Author: francesc.perez@stucom.com - Version 1.1.0");
        jLabel2.setRequestFocusEnabled(false);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 317, 717, -1));

        dateOfBirth.setMaximumSize(new java.awt.Dimension(350, 22));
        dateOfBirth.setMinimumSize(new java.awt.Dimension(350, 22));
        dateOfBirth.setPreferredSize(new java.awt.Dimension(350, 22));
        getContentPane().add(dateOfBirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 230, 400, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Name");
        jLabel3.setMaximumSize(new java.awt.Dimension(100, 22));
        jLabel3.setMinimumSize(new java.awt.Dimension(100, 22));
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 22));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 66, 150, -1));

        email.setMaximumSize(new java.awt.Dimension(400, 22));
        email.setMinimumSize(new java.awt.Dimension(400, 22));
        email.setPreferredSize(new java.awt.Dimension(400, 22));
        email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emailKeyTyped(evt);
            }
        });
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 108, 294, -1));

        checkEmailField.setText("CHECK");
        checkEmailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkEmailFieldActionPerformed(evt);
            }
        });
        getContentPane().add(checkEmailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(666, 107, -1, -1));

        EmailIsValidCheck.setEnabled(false);
        EmailIsValidCheck.setFocusable(false);
        EmailIsValidCheck.setRequestFocusEnabled(false);
        getContentPane().add(EmailIsValidCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(748, 107, -1, 26));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 6));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Phone");
        jLabel4.setMaximumSize(new java.awt.Dimension(100, 22));
        jLabel4.setMinimumSize(new java.awt.Dimension(100, 22));
        jLabel4.setPreferredSize(new java.awt.Dimension(100, 22));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 151, 150, -1));

        phone.setMaximumSize(new java.awt.Dimension(400, 22));
        phone.setMinimumSize(new java.awt.Dimension(400, 22));
        phone.setPreferredSize(new java.awt.Dimension(400, 22));
        phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                phoneKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                phoneKeyTyped(evt);
            }
        });
        getContentPane().add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 151, 294, -1));

        checkPhoneField.setText("CHECK");
        checkPhoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkPhoneFieldActionPerformed(evt);
            }
        });
        getContentPane().add(checkPhoneField, new org.netbeans.lib.awtextra.AbsoluteConstraints(666, 150, -1, -1));

        PhoneValidCheck.setEnabled(false);
        PhoneValidCheck.setFocusable(false);
        PhoneValidCheck.setRequestFocusEnabled(false);
        getContentPane().add(PhoneValidCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(748, 150, -1, 26));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("ZIP Code");
        jLabel6.setMaximumSize(new java.awt.Dimension(100, 22));
        jLabel6.setMinimumSize(new java.awt.Dimension(100, 22));
        jLabel6.setPreferredSize(new java.awt.Dimension(100, 22));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 194, 150, -1));

        zipCode.setMaximumSize(new java.awt.Dimension(400, 22));
        zipCode.setMinimumSize(new java.awt.Dimension(400, 22));
        zipCode.setPreferredSize(new java.awt.Dimension(400, 22));
        zipCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                zipCodeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                zipCodeKeyTyped(evt);
            }
        });
        getContentPane().add(zipCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 194, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void showInsert() {
        if (!email.getText().isEmpty() && !phone.getText().isEmpty() && (zipCode.getText().length() >= 5 && zipCode.getText().length() <= 10) && !name.getText().isEmpty() && !nif.isEditable()) {
            insert.setEnabled(true);
        } else {
            insert.setEnabled(false);
        }
    }

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        nif.setEditable(true);
        nif.setText("");
        name.setText("");
        email.setText("");
        phone.setText("");
        zipCode.setText("");
        photo.setIcon(null);
        //We reset the calendar date to the current date ...
        LocalDate dateLocate = LocalDate.now();
        ZoneId systemTimeZone = ZoneId.systemDefault();
        ZonedDateTime zonedDateTime = dateLocate.atStartOfDay(systemTimeZone);
        Date dateUtil = java.sql.Date.from(zonedDateTime.toInstant());
        Calendar calendar = Calendar.getInstance();
        calendar.setTime(dateUtil);
        DateModel<Calendar> dateModel = (DateModel<Calendar>) dateOfBirth.getModel();
        dateModel.setValue(calendar);
        //... but do not display it in the JDatePicker box
        dateOfBirth.getModel().setValue(null);
        insert.setEnabled(false);
        // We reset the phone and email checks
        EmailIsValidCheck.setSelected(false);
        PhoneValidCheck.setSelected(false);
    }//GEN-LAST:event_resetActionPerformed

    private void nifKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nifKeyTyped
        if (!isNumber(evt.getKeyChar()) && evt.getKeyChar() != KeyEvent.VK_BACK_SPACE && evt.getKeyChar() != KeyEvent.VK_DELETE) {
            JOptionPane.showMessageDialog(this, "Type only numbers [0-9]", this.getTitle(), JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }
        nif.setForeground(Color.BLACK);
    }//GEN-LAST:event_nifKeyTyped

    private void nameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyTyped
        if (!isLetter(evt.getKeyChar()) && evt.getKeyChar() != KeyEvent.VK_BACK_SPACE && evt.getKeyChar() != KeyEvent.VK_DELETE) {
            JOptionPane.showMessageDialog(this, "Type only uppercase or lowercase letters, hyphens, and whitespace.", this.getTitle(), JOptionPane.ERROR_MESSAGE);
            evt.consume();
        } else if (isLetter(evt.getKeyChar()) || evt.getKeyChar() == KeyEvent.VK_BACK_SPACE || evt.getKeyChar() == KeyEvent.VK_DELETE) {
            showInsert();
        }
        name.setForeground(Color.black);
    }//GEN-LAST:event_nameKeyTyped

    private void nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameKeyReleased
        showInsert();
    }//GEN-LAST:event_nameKeyReleased

    private void photoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_photoMouseClicked
        photo.setIcon(null);
    }//GEN-LAST:event_photoMouseClicked

    private void nifKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nifKeyReleased
        if (nif.getText().length() == 8) {
            nif.setText(calculateNifLetter(nif.getText()));
            nif.setEditable(false);
            showInsert();
        }
    }//GEN-LAST:event_nifKeyReleased

    private void nifKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nifKeyPressed
        if (nif.getText().length() == 8) {
            evt.consume();
            nif.setText(calculateNifLetter(nif.getText()));
            nif.setEditable(false);
            showInsert();
        }
    }//GEN-LAST:event_nifKeyPressed

    private void checkEmailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkEmailFieldActionPerformed
        if (!checkEmailAddress(email.getText()) && email.getText().length() < 1) {
            JOptionPane.showMessageDialog(this, "Please introduce an email first before checking for validity.", this.getTitle(), JOptionPane.ERROR_MESSAGE);
            EmailIsValidCheck.setSelected(false);
        } else {
            if (!checkEmailAddress(email.getText())) {
                JOptionPane.showMessageDialog(this, "Email not valid, remember, type only lowercase or uppercase letters, hyphens and do not leave trailing whitespaces.\nName, must not be less than 1 character and more than 64 characters.\nDomain and sub-domain must not be less than 2 characters and more than 9 characters.\n\nAn email should look like this 'example@example.com'", this.getTitle(), JOptionPane.ERROR_MESSAGE);
                EmailIsValidCheck.setSelected(false);
            } else {
                JOptionPane.showMessageDialog(this, "Email specified is valid.", this.getTitle(), JOptionPane.INFORMATION_MESSAGE);
                EmailIsValidCheck.setSelected(true);
            }
        }
    }//GEN-LAST:event_checkEmailFieldActionPerformed

    private void emailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyReleased
        showInsert();
    }//GEN-LAST:event_emailKeyReleased

    private void emailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailKeyTyped
        EmailIsValidCheck.setSelected(false);
    }//GEN-LAST:event_emailKeyTyped

    private void phoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneKeyReleased
        showInsert();
    }//GEN-LAST:event_phoneKeyReleased

    private void phoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_phoneKeyTyped
        PhoneValidCheck.setSelected(false);
    }//GEN-LAST:event_phoneKeyTyped

    private void checkPhoneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkPhoneFieldActionPerformed
        if (!checkPhoneNumber(phone.getText()) && phone.getText().length() < 1) {
            JOptionPane.showMessageDialog(this, "Please introduce a phone number first before checking for validity.", this.getTitle(), JOptionPane.ERROR_MESSAGE);
            PhoneValidCheck.setSelected(false);
        } else {
            if (!checkPhoneNumber(phone.getText())) {
                JOptionPane.showMessageDialog(this, "Phone not valid, remember, type only numbers, do not leave trailing whitespaces.\nPhone, must not be less than 1 number and more than 9 numbers.\n\nA phone number should look like this '945125691'", this.getTitle(), JOptionPane.ERROR_MESSAGE);
                PhoneValidCheck.setSelected(false);
            } else {
                JOptionPane.showMessageDialog(this, "Phone specified is valid.", this.getTitle(), JOptionPane.INFORMATION_MESSAGE);
                PhoneValidCheck.setSelected(true);
            }
        }
    }//GEN-LAST:event_checkPhoneFieldActionPerformed

    private void zipCodeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_zipCodeKeyReleased
        showInsert();
    }//GEN-LAST:event_zipCodeKeyReleased

    private void zipCodeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_zipCodeKeyTyped
        showInsert();
        if (!Character.isDigit(evt.getKeyChar()) && evt.getKeyChar() != KeyEvent.VK_BACK_SPACE && evt.getKeyChar() != KeyEvent.VK_DELETE && evt.getKeyChar() != KeyEvent.VK_MINUS && evt.getKeyChar() != KeyEvent.VK_SPACE) {
            JOptionPane.showMessageDialog(this, "Type only numbers [0-9]", this.getTitle(), JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }
        if ((zipCode.getText().length() > 4 && !checkZipCodeTyping(zipCode.getText()))) {
            JOptionPane.showMessageDialog(this, "ZIP Code is invalid.", this.getTitle(), JOptionPane.ERROR_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_zipCodeKeyTyped

    private void nifFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nifFocusGained
        if ((nif.getText().equals("Enter NIF number, letter is calculated (e.g., 12345678)"))) {
            nif.setText("");
        }
    }//GEN-LAST:event_nifFocusGained

    private void nifFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nifFocusLost
        if ((nif.getText().length() < 1)) {
            nif.setText("Enter NIF number, letter is calculated (e.g., 12345678)");
            nif.setForeground(Color.gray);
        }
    }//GEN-LAST:event_nifFocusLost

    private void nameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusGained
        if ((name.getText().equals("Enter full name"))) {
            name.setText("");
        }
    }//GEN-LAST:event_nameFocusGained

    private void nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusLost
        if ((name.getText().length() < 1)) {
            name.setText("Enter full name");
            name.setForeground(Color.gray);
        }
    }//GEN-LAST:event_nameFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox EmailIsValidCheck;
    private javax.swing.JCheckBox PhoneValidCheck;
    private javax.swing.JButton checkEmailField;
    private javax.swing.JButton checkPhoneField;
    private org.jdatepicker.JDatePicker dateOfBirth;
    private javax.swing.JTextField email;
    private javax.swing.JButton insert;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField nif;
    private javax.swing.JTextField phone;
    private javax.swing.JLabel photo;
    private javax.swing.JButton reset;
    private javax.swing.JTextField zipCode;
    // End of variables declaration//GEN-END:variables

}
